base_url: "http://localhost:8080" # platform base url
output_folder: "/home/severin/Downloads/" # Folder where the files are exported to
platform: "EHRBASE" # BETTER or EHRBASE, BETTER should work also for all other platfoms, EHRBASE has currently smt wrong in the body return (already reported)
export_type: "CANONICAL" # FLAT only supported for BETTER (the view is in resoures).
steps: 100000 # how much compositions are mapped per AQL e.g. 10000 per process, the bigger the number to longer queries take

auth:
  username: "myuser"
  password: "myPassword432"

logging:
  cmd_level: "info" # what you see on the cmd INFO DEBUG ERROR are supported
  file_level: "debug" # what ends up in the log file INFO DEBUG ERROR are supported


#atest